### ISSUE TITLE
The pretrained weights "Flow_G.pth" are not loaded when generating videos.

### ISSUE THREAD

**Issue by kult0922** [zhangzjn/DTVNet#1]
When generating videos, I found out that the pretrained weights "Flow_G.pth" are not loaded. Is this an expected behavior of the model?

**Comment by zhangzjn** [comment]
@kult0922 
Yes. The test code we released uses randomly selected motion vector to generate various video clips. Also, you can first load ARFlow to generate a special motion vector from a special video clip and then use it to generate target video clip. Generally, flow model is only used during the training phase.

**Comment by kult0922** [comment]
Oh, OK, thanks!
