### ISSUE TITLE
Generated video is not of the sample output quality.

### ISSUE THREAD

**Issue by kult0922** [zhangzjn/DTVNet#2]
I've tried generating videos using the provided pretrained model, but the result is not as clean as the one provided in the sample output, and the PSNR and SSIM values are quite low (lower than the results provided by the paper). 

I used the provided "DTV_G.pth" and optical flow npy files to generate the videos. I also used the parameters described in configs/sky_timelapse.json without any changes.

The video I generated is the bottom one. I've also put the sample output video for reference. (upper: sample output, bottom: my result)

![07U1fSrk9oI_1_4_video](https://user-images.githubusercontent.com/38486600/100240126-8c82e600-2f75-11eb-8a81-6c9edcf168a6.gif)
![07U1fSrk9oI_1](https://user-images.githubusercontent.com/38486600/100240131-8e4ca980-2f75-11eb-958c-429471659ec1.gif)

Am I generating the videos wrongly by any means?

**Comment by zhangzjn** [comment]
@kult0922 
You may randomly sample the motion vector multiple times. In fact, some motion vectors are not suitable for a special scene, so you should try it many times..

**Comment by kult0922** [comment]
@zhangzjn 
OK, thanks!
